/* Generates src/data/site.js from the site of record. Never hand-edit the output.
   Applies the 20 Sep 2026 rebrand: Laundrylegends -> Linen Legends (§12.1 of the build plan). */
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs';

const src = readFileSync('site/laundrylegends-site.html', 'utf8');
const slice = (start, end) => {
  const i = src.indexOf(start);
  if (i < 0) throw new Error(`marker not found: ${start}`);
  const j = src.indexOf(end, i);
  return src.slice(i, j + end.length);
};
const evalBlock = (code, name) => new Function(`${code}; return ${name};`)();

const FAQS = evalBlock(slice('const FAQS = [', '\n];'), 'FAQS');

const rebrand = (s) =>
  s.replaceAll('Laundrylegends', 'Linen Legends')
   .replaceAll('laundrylegends.com.au', 'linenlegends.com.au');

const faqs = FAQS.map(([q, a]) => ({ q: rebrand(q), a: rebrand(a) }));

const site = {
  brand: 'Linen Legends',
  tagline: 'We wash it well',
  domain: 'https://linenlegends.com.au',
  region: 'Brisbane, Logan & South East Queensland',
  club: { name: 'Legends Club', plans: [
    { key: 'plan1', name: 'Solo', blurb: 'One to two people. One standard bag each week.', loads: '≈ 1–2 loads per week' },
    { key: 'plan2', name: 'Household', blurb: 'Families of three to four. Two bags each week.', loads: '≈ 2–4 loads per week' },
    { key: 'plan3', name: 'Full House', blurb: 'Larger households. Three bags each week.', loads: '≈ 4–6 loads per week' },
  ]},
  faqs,
  /* Compliance sentinels — verbatim from the source of record, brand-substituted only.
     verify/sentinels.mjs asserts every one of these appears in the built site. */
  legal: {
    footerEntity: 'Company name and ABN to be published on registration',
    gst: 'All prices include GST and are in AUD',
    owned: 'Australian owned and operated',
    phone: 'Phone line being connected',
    email: 'Email to be published',
    ndis: rebrand('We are not currently a registered NDIS provider, so we cannot invoice the NDIA directly for agency-managed plans.'),
    asnzs: 'We do not currently hold accreditation to process clinical or healthcare linen (AS/NZS 4146).',
    acl: 'This guarantee sits on top of your rights under the Australian Consumer Law. Nothing on this page limits or replaces those rights.',
    contractor: 'This is an independent contracting arrangement, not employment.',
    pricingReview: 'Launch pricing, under review and subject to change.',
    draftPolicies: 'Drafts for legal review and not yet in force.',
  },
};

mkdirSync('src/data', { recursive: true });
writeFileSync('src/data/site.js',
  '/* GENERATED by tools/extract_site_data.mjs — do not edit. */\n' +
  'export default ' + JSON.stringify(site, null, 2) + ';\n');
console.log(`site.js written: ${faqs.length} FAQs, ${Object.keys(site.legal).length} sentinels`);
